### ISSUE TITLE
[future]图片输出

### ISSUE THREAD

**Issue by YouYouLip** [forchannot/nonebot-plugin-gshisbanner#1]
感觉可以把历史卡池改为图片输出会更好，这样看起来会更加简洁而且美观

**Comment by YouYouLip** [comment]
而且感觉up时间几号到几号好像有点多余（？）毕竟只要看最后一次复刻的时间就足够了

**Comment by forchannot** [comment]
emmm，怎么说呢，第一个建议当初做这个项目就考虑过了，但是我个人能力不够，不会html和js绘图，也没有可用的好看的模板让我pil画图，如果有兴趣可以pr下😂
第二个建议的话，可以考虑把小时去掉，但是历史时间几号还是留着，毕竟有人有这个需要
