### ISSUE TITLE
[问题]卡池查询没反应，历史卡池能正常返回

### ISSUE THREAD

**Issue by mengluo04** [forchannot/nonebot-plugin-gshisbanner#18]

**Comment by forchannot** [comment]
日志呢

**Comment by mengluo04** [comment]
> 日志呢

啥都没有，就一个接收到请求，显示complate，没了

**Comment by forchannot** [comment]
命令怎么发的，看看命令，我这里没问题

**Comment by mengluo04** [comment]
> 命令怎么发的，看看命令，我这里没问题

![image](https://github.com/forchannot/nonebot-plugin-gshisbanner/assets/32565940/40bc5c45-e9a3-4b71-a0f9-f888828bd3ca)
这样

**Comment by forchannot** [comment]
4.6都还没上哪来的卡池，数据来源https://github.com/KeyPJ/FetchData ，数据更新后需要执行刷新历史卡池命令

**Comment by mengluo04** [comment]
> 4.6都还没上哪来的卡池，数据来源https://github.com/KeyPJ/FetchData

我傻了，那没事了
