### ISSUE TITLE
[WinError 64] 指定的网络名不再可用。

### ISSUE THREAD

**Issue by zuixiaoxiao** [forchannot/nonebot-plugin-gshisbanner#3]
如题
![image](https://user-images.githubusercontent.com/108536651/230727580-37fd430e-fc41-4dee-88cd-46e7de7a0c64.png)
![image](https://user-images.githubusercontent.com/108536651/230727602-75385b67-5b8d-4673-86cc-39cb2922d5ef.png)
![image](https://user-images.githubusercontent.com/108536651/230727613-94e20e74-60fc-482e-aed1-d373313c640e.png)
发送相关指令都报错不可用

**Comment by forchannot** [comment]
请确保你使用的是最新版本

**Comment by zuixiaoxiao** [comment]
> 请确保你使用的是最新版本

刚下的

**Comment by zuixiaoxiao** [comment]
> > 请确保你使用的是最新版本
> 
> 刚下的

![image](https://user-images.githubusercontent.com/108536651/230728674-723d4a3b-e018-4c29-8713-b417f53f6dd5.png)

**Comment by forchannot** [comment]
检查下服务器网络问题，https://ghproxy.com/https://raw.githubusercontent.com/forchannot/nonebot-plugin-gshisbanner/main/data/genshin_history/alias.json

https://genshin-gacha-banners.52v6.com/data/character.json

看看这两个是否能打得开，我这边无法复现

**Comment by zuixiaoxiao** [comment]
> Owner

第二个打不开
![image](https://user-images.githubusercontent.com/108536651/230729188-5b5cb6e4-6b51-40a5-ad0a-a39a2b399434.png)

**Comment by forchannot** [comment]
https://banners.52v6.com/data/character.json 呢，很奇怪，我这边是没问题的

**Comment by zuixiaoxiao** [comment]
> https://banners.52v6.com/data/character.json 呢，很奇怪，我这边是没问题的

这个可以大打开

**Comment by forchannot** [comment]
执行
 ```nb plugin update nonebot-plugin-gshisbanner -i https://pypi.org/simple```
试试，然后确保版本更新为0.4.2后再尝试一下，在配置项中新增三个host可选，可在readme查看

**Comment by forchannot** [comment]
可以试试最新0.4.3

**Comment by zuixiaoxiao** [comment]
![image](https://user-images.githubusercontent.com/108536651/230732989-e133b453-0189-4184-978c-5fc7d6d5d79d.png)
emm，新报错，查看版本卡池的还是不是，角色历史卡池和刷新可以了

**Comment by zuixiaoxiao** [comment]
![image](https://user-images.githubusercontent.com/108536651/230732989-e133b453-0189-4184-978c-5fc7d6d5d79d.png)
emm，新报错，查看版本卡池的还是不是，角色历史卡池和刷新可以了

**Comment by forchannot** [comment]
已修复，等待action跑完就可以更新了，忘了用get了（恼
